package com.dkhalife.projects;

/**
 * 
 * @author Dany Khalife
 * @version 1.0
 * @since December 09, 2012
 * 
 */
public class Wall {
	public int room1;
	public int room2;

	/**
	 * 
	 * A wall is a separation between two rooms (their order doesn't matter)
	 * 
	 * @author Dany Khalife
	 * @param r1 The first room
	 * @param r2 The second room
	 * 
	 */
	public Wall(int r1, int r2) {
		room1 = r1;
		room2 = r2;
	}

	/**
	 * 
	 * Two Walls are considered equal if they block the same rooms The first
	 * half of the code was automatically generated by eclipse
	 * 
	 * @author Dany Khalife
	 * 
	 */
	public boolean equals(Object obj) {
		if (this == obj)
			return true;

		if (obj == null)
			return false;

		if (getClass() != obj.getClass())
			return false;

		Wall other = (Wall) obj;
		if (room1 == other.room1 && room2 == other.room2) {
			return true;
		}

		if (room1 == other.room2 && room2 == other.room1) {
			return true;
		}

		return false;
	}
}